# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Template workflow to test the private Spot endpoints of the
# python-kraken-sdk.
#
# Runs tests for:
#   * Spot REST clients
#   * Spot websocket clients
#

name: Test Spot

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true
    secrets:
      SPOT_API_KEY:
        required: true
      SPOT_SECRET_KEY:
        required: true

permissions: read-all

jobs:
  Test-Spot:
    name: Test ${{ inputs.os }} ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Update Pip
        run: |
          python -m pip install --user --upgrade pip

      - name: Install package
        run: python -m pip install --user ".[test]"

      ##    Unit tests of private Spot REST clients and endpoints
      ##
      - name: Testing Spot REST endpoints
        env:
          SPOT_API_KEY: ${{ secrets.SPOT_API_KEY }}
          SPOT_SECRET_KEY: ${{ secrets.SPOT_SECRET_KEY }}
        run: pytest -vv -m "spot_auth and not spot_websocket" tests

      ##    Unit tests of Spot websocket clients
      ##
      - name: Testing Spot websocket client
        env:
          SPOT_API_KEY: ${{ secrets.SPOT_API_KEY }}
          SPOT_SECRET_KEY: ${{ secrets.SPOT_SECRET_KEY }}
        run: pytest -vv -m spot_websocket tests
