# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Template workflow to test the public NFT endpoints
# of the python-kraken-sdk.
#

name: Test NFT

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true

permissions: read-all

jobs:
  Test-NFT:
    name: Test ${{ inputs.os }} ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Update Pip
        run: |
          python -m pip install --user --upgrade pip

      - name: Install package
        run: python -m pip install --user ".[test]"

      ##    Unit tests of the public Spot NFT clients and endpoints
      ##
      - name: Testing Spot NFT endpoints
        run: pytest -vv -m "nft and not nft_auth" tests
